### ISSUE TITLE
Remove `SELECTED` property as from the select tag as label

### ISSUE THREAD

**Issue by evertramos** [bkzl/vue-float-label#10]
Hello @bkzl ,

I would suggest removing the `[selected]`property from the select, as the label... 

It happens to me that when loading and edit select we must have it filled with some data and this property should be used by another option, so might cause inconsistency.

So would be:

````
        case 'select':
          return this.formEl.querySelector('option[disabled]').innerHTML
````

Just a suggestions.

Thanks!

**Comment by bkzl** [comment]
I think I will add `label` property so there will be an option to override query or placeholder attr for any element.

**Comment by bkzl** [comment]
@evertramos I published a new version. With the new features, you should be able to achieve what you needed (v-model, labels for preselected values). There are some new examples of usage at [Demo.vue](https://github.com/bkzl/vue-float-label/blob/master/demo/Demo.vue).
