### ISSUE TITLE
Error on Production

### ISSUE THREAD

**Issue by evertramos** [bkzl/vue-float-label#2]
I got the following error when running:

```
npm run production
``` 

```
 error

/js/app.js from UglifyJs
Unexpected token punc «(», expected punc «:» [./~/vue-float-label/vue-float-label.js:4,0][/js/app.js:22266,10]
```

**Update 1**

I am using Laravel on Windows, so my full production execution is:

```
"production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
```
Thanks!

**Comment by bkzl** [comment]
Do you use compiled CDN version or npm package?

**Comment by evertramos** [comment]
npm package

**Comment by bkzl** [comment]
I didn't look into it, yet.

@lmartins Webpack 1 or 2?

What's the easiest way to reproduce your dev environment?

**Comment by lmartins** [comment]
@bkzl 

Webpack 2 in my case.
But I've just noticed something that puzzles me. If I set the devtool to `cheap-module-eval-source-map` it compiles without an issue.

**Comment by bkzl** [comment]
Ahh, I'm pretty sure the problem happens because babel doesn't compile source of external packages in your setup. I'll change the entry-point file to the compiled source from /dist.
