### ISSUE TITLE
[feature request] Manually show label

### ISSUE THREAD

**Issue by evertramos** [bkzl/vue-float-label#4]
Wouldn´t be cool if we could activate/show the label mannually for some objects that are not standard inputs? 

This might would substitute the #3. 

I would suggest something like this:

````
<float-label active>
  <input placeholder="Birthday" type="date">
</float-label>
````

It should only take care about the coloring when the focus is in the current input, it should get the float label active color and user leave it turn to regular float label color (e.g. grey).

**Comment by evertramos** [comment]
Sorry not being able to send a PR, I am still learning js and css....

**Comment by bkzl** [comment]
No worries. Thank you for your engagement! I'm not sure about the proposed API tho. What do you think about the possibility to provide a function through the property? The floating label will be active if the function returns true. So, let's say:

```vue
<template>
  <float-label on="isLabelActive">
    <input placeholder="Birthday" type="date">
  </float-label>
</template>

<script>
export default {
  computed: {
    isLabelActive () {
      return true
    }
  }
}
</script>
```

**Comment by evertramos** [comment]
Thanks @bkzl!

I think it sounds good to me. 

Very close to what I have done as work around:

````
<label class="vfl-label vfl-label-on-input" :class="{'vfl-label-on-focus' : onFocusBirthday}">
    Birthday
</label>
````

**Comment by evertramos** [comment]
Just one more comment, as I am using the portuguese (brasil) language the date format we normally use is _DD/MM/YYYY_ so, I am getting the *on-focus* class only after I start typing the year... so I got an `@click`  and `@keydown` to activate it as well, so I could have the nice and smoth label activated when hit the element.
